[build-system]
requires = [
    "setuptools >= 40.9.0",
    "wheel",
]

[tool.black]
line-length = 100
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

# vim: ts=4 expandtab
